server:
  port: ${SERVER_PORT:9090}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:db_travel}?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

alipay:
  appId: ${ALIPAY_APP_ID:}
  appPrivateKey: ${ALIPAY_APP_PRIVATE_KEY:}
  alipayPublicKey: ${ALIPAY_PUBLIC_KEY:}
  notifyUrl: ${ALIPAY_NOTIFY_URL:}

fileBaseUrl: ${FILE_BASE_URL:http://localhost:${server.port}}
